### ISSUE TITLE
Add macOS container action support

### ISSUE THREAD

**Issue by maximbircu** [vgaidarji/android-github-actions-build#6]
# Abstract

I am trying to assemble an Android/iOS multi-platform project using this action. The Android AAR libs generation works perfectly, but I am not able  to  generate iOS frameworks because this is not possible on a non-macOS machine :disappointed:

<img width="700" alt="issue2" src="https://user-images.githubusercontent.com/12527390/77847865-d9d16c80-71c8-11ea-9581-5e2ddddfdea3.png">

I tried to use the action on a macOS machine, but it seems that this system is not supported.

<img width="435" alt="issue1" src="https://user-images.githubusercontent.com/12527390/77847878-ece43c80-71c8-11ea-817c-9a23f5f1e40d.png">

# Requirements
Add macOS container action support.

# Testing scenario
Try to assemble any Android project on a macOS machine using the workflow config file attached below.

```YML
name: CI

on: push

jobs:
  build:
    name: "Assemble artifacts"
    runs-on: macos-latest
    steps:
      # Checkout
      - name: SCM
        uses: actions/checkout@v2

      # Assemble artifacts
      - name: Assemble
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew assemble"
```
