### ISSUE TITLE
gradlew not found

### ISSUE THREAD

**Issue by Qoyyuum** [vgaidarji/android-github-actions-build#7]
Unable to `gradlew assembleDebug` for some odd reason. I can confirm that the working directory does have a `gradlew` file.

```
ls \bsl\src-capacitor\android


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       05/06/2020   9:25 AM                .gradle
d-----       01/05/2020   2:40 PM                app
d-----       03/06/2020   5:46 PM                capacitor-cordova-android-plugins
d-----       01/05/2020   2:40 PM                gradle
-a----       01/05/2020   2:40 PM           1589 .gitignore
-a----       05/06/2020   9:23 AM            108 build-script.ps
-a----       01/05/2020   2:40 PM            594 build.gradle
-a----       03/06/2020   5:46 PM            207 capacitor.settings.gradle
-a----       01/05/2020   2:40 PM            730 gradle.properties
-a----       01/05/2020   2:40 PM           4971 gradlew
-a----       01/05/2020   2:40 PM           2314 gradlew.bat
-a----       01/05/2020   2:40 PM            208 settings.gradle
```

Here's a sample of my workflow yaml file for your reference:
```
jobs:
  build-capacitor:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: bsl

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS Environment ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.2
        with:
            node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx quasar build -m capacitor -T android --skip-pkg
      
  build-android:
    needs: [build-capacitor]
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        working-directory: bsl/src-capacitor/android
        
    steps:
      - name: Android Build
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew assembleDebug"
```

Here's the error log:

```
Run vgaidarji/android-github-actions-build@v1.0.1
  with:
    args: ./gradlew assembleDebug
/usr/bin/docker run --name d3e2c2b307e9664f99bab6eb1cf2446448_bf10ee --label 3888d3 --workdir /github/workspace --rm -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/jari2ku/jari2ku":"/github/workspace" 3888d3:e2c2b307e9664f99bab6eb1cf2446448 ./gradlew assembleDebug
sh: 1: ./gradlew: not found
```
